version: "3.9"

services:
  id-gen-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-gen-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      OUTPUT_ROOT: /data/output
    volumes:
      - ./output:/data/output
